const PLAYERS=window.ATHLETE_PLAYERS||[], MLB=window.MLB_TEAMS||{};const CURRENT=2026,RECENT=6,L='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),ALL=L.flatMap(a=>L.map(b=>a+b)),DOUB=L.map(x=>x+x);

const TEAM_THEMES={
ANA:['#0b1f3a','#132b4c','#1d3b61','#ba0021','#ffffff','#27496d'],ARI:['#1b1115','#2b171d','#3b2028','#a71930','#ffffff','#4a2831'],ATL:['#081b33','#102b4c','#173b62','#ce1141','#ffffff','#204b73'],BAL:['#17120e','#241b14','#33251a','#df4601','#ffffff','#3e2c1f'],BOS:['#071a32','#102b4d','#183b63','#bd3039','#ffffff','#224b73'],CHC:['#071a3a','#0e2a55','#153765','#cc3433','#ffffff','#183c6d'],CHW:['#080b0e','#15191e','#20262d','#f4f4f4','#080b0e','#282f36'],CIN:['#230b0e','#351216','#48191f','#c6011f','#ffffff','#552028'],CLE:['#071b2e','#102b45','#173b59','#e31937','#ffffff','#20486a'],COL:['#120d20','#211735','#302248','#c4ced4','#151018','#3c2c57'],DET:['#07182b','#10263e','#18344f','#fa4616','#ffffff','#20415f'],FLA:['#061d2b','#0d2d40','#153d54','#00a3e0','#ffffff','#174b64'],HOU:['#071b31','#102b4b','#183b60','#eb6e1f','#ffffff','#204a70'],KCR:['#071c36','#102e55','#173d6b','#7ab2dd','#08182b','#204b79'],LAD:['#061d3b','#0c2e59','#123d72','#ffffff','#005a9c','#174a83'],MIL:['#07192f','#102943','#183852','#ffc52f','#101820','#204561'],MIN:['#07182d','#102740','#183650','#d31145','#ffffff','#20445f'],NYM:['#071d3a','#102f58','#173f70','#ff5910','#ffffff','#204c7d'],NYY:['#071527','#0e2239','#16304a','#ffffff','#0c2340','#1d3c59'],OAK:['#071f18','#0d3326','#154533','#efb21e','#10261d','#1b5640'],PHI:['#071b35','#102c50','#183b65','#e81828','#ffffff','#204a75'],PIT:['#17140a','#27210f','#382e14','#fdb827','#16130a','#473a19'],SDP:['#1d160b','#302311','#433118','#ffc425','#20180c','#513c1e'],SEA:['#061c22','#0d2e35','#154049','#c4ced4','#062b33','#1c515b'],SFG:['#21110b','#341a10','#472316','#fd5a1e','#ffffff','#552a1a'],STL:['#071a33','#102a4c','#173961','#c41e3a','#ffffff','#204872'],TBD:['#071b35','#102c50','#183b65','#8fbce6','#092544','#204a75'],TEX:['#071b3a','#102d59','#173e73','#c0111f','#ffffff','#204b82'],TOR:['#071d3d','#102f5d','#174078','#134a8e','#ffffff','#205089'],WSN:['#230b10','#351218','#481921','#ab0003','#ffffff','#552029']};
function applyTheme(){
 const root=document.documentElement,m=meta();
 document.body.className='theme-'+m.theme;
 if(cfg.scope==='team'){
   const t=TEAM_THEMES[cfg.choice]||TEAM_THEMES.CHW;
   ['--bg','--panel','--panel2','--accent','--accentInk','--soft'].forEach((v,i)=>root.style.setProperty(v,t[i]));
   root.style.setProperty('--line',t[2]);
 }else{
   ['--bg','--panel','--panel2','--accent','--accentInk','--soft','--line'].forEach(v=>root.style.removeProperty(v));
 }
}

const LEGACY={whitesox:'CHW',cubs:'CHC',chicago:'chicago'};let cfg=JSON.parse(localStorage.getItem('aa-v31-config')||localStorage.getItem('aa-v30-config')||'{"scope":"team","choice":"CHW","era":"modern","mode":"alphabet"}');cfg.choice=LEGACY[cfg.choice]||cfg.choice;if(cfg.scope==='league')cfg.choice='MLB';
let current='AA',idx=0,lastRandom=null,hintLevel=0,hintPlayerId=null,firstNameShown=false;const $=x=>document.getElementById(x);
function key(){return `aa-v31:${cfg.scope}:${cfg.choice}:${cfg.era}`};function prog(){return JSON.parse(localStorage.getItem(key())||'{"solved":{},"revealed":{},"deferred":[]}')}function put(p){localStorage.setItem(key(),JSON.stringify(p))}function saveCfg(){localStorage.setItem('aa-v31-config',JSON.stringify(cfg))}
function meta(){if(cfg.scope==='league')return{name:'Major League Baseball',short:'MLB',first:1871,theme:'mlb'};if(cfg.scope==='region')return{name:'Chicago Region · MLB',short:'Chicago MLB',first:1876,theme:'chicago'};let m=MLB[cfg.choice]||MLB.CHW;return{name:m.name,short:m.short,first:m.first,theme:'team'}}
function teamYears(p){if(cfg.scope==='league'){let a=Object.values(p.teams);return a.length?[Math.min(...a.map(x=>x[0])),Math.max(...a.map(x=>x[1]))]:null}if(cfg.scope==='region'){let a=['CHC','CHW'].filter(k=>p.teams[k]).map(k=>p.teams[k]);return a.length?[Math.min(...a.map(x=>x[0])),Math.max(...a.map(x=>x[1]))]:null}return p.teams[cfg.choice]||null}
function eraRange(e){let f=meta().first;if(e==='current')return[Math.max(f,CURRENT-RECENT+1),CURRENT];if(e==='modern')return[Math.max(f,2000),CURRENT];if(e==='classic')return[f,Math.min(1999,CURRENT)];return[f,CURRENT]}
function pool(){let [s,e]=eraRange(cfg.era);return PLAYERS.filter(p=>{let y=teamYears(p);return y&&y[0]<=e&&y[1]>=s})}function byI(){let b={};for(let p of pool())(b[p.i]??=[]).push(p);return b}function found(i){return prog().solved[i]||[]}function viable(){let b=byI();return ALL.filter(i=>b[i]?.length)}function seq(){let b=byI();return (cfg.mode==='double'?DOUB:ALL).filter(i=>b[i]?.length)}
function resetHint(){hintLevel=0;hintPlayerId=null;firstNameShown=false}function pick(){resetHint();let b=byI(),v=viable();if(cfg.mode==='random'){let q=v.filter(i=>found(i).length<(b[i]?.length||0)&&i!==lastRandom);if(!q.length)q=v.filter(i=>i!==lastRandom);current=q[Math.floor(Math.random()*q.length)]||v[0]}else{let s=seq();current=s[idx%s.length]||v[0]}lastRandom=current;render()}
function setScope(s){cfg.scope=s;cfg.choice=s==='region'?'chicago':s==='league'?'MLB':'CHW';saveCfg();idx=0;buildChoices();pick()}function setChoice(c){cfg.choice=c;saveCfg();idx=0;buildChoices();pick()}function setEra(e){cfg.era=e;saveCfg();idx=0;pick()}function setMode(m){cfg.mode=m;saveCfg();idx=0;pick()}function advance(){if(cfg.mode==='random')pick();else{idx++;pick()}}
function years(r){return r[0]+'–'+String(r[1]).slice(-2)}function updateEra(){for(let e of ['current','modern','classic','all'])$(e+'Years').textContent=years(eraRange(e));let r=eraRange(cfg.era);$('eraNote').textContent=`${r[0]}–${r[1]}: a player qualifies if any ${meta().short} season overlaps this range.`}
function buildChoices(){let box=$('scopeChoices');box.innerHTML='';let cs=[];if(cfg.scope==='region')cs=[['chicago','Chicago (Cubs + White Sox)']];else if(cfg.scope==='team')cs=Object.entries(MLB).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([k,v])=>[k,v.name]);else cs=[['MLB','All MLB franchises']];for(let [k,n] of cs){let b=document.createElement('button');b.textContent=n;b.className=cfg.choice===k?'active':'';b.onclick=()=>setChoice(k);box.appendChild(b)}$('scopeNote').textContent=cfg.scope==='region'?'Chicago Region currently includes MLB only. Bears, Bulls and Blackhawks can join later.':cfg.scope==='league'?'Any player from the 30 current MLB franchise lineages qualifies.':'Choose any current MLB franchise. Historical names and relocations follow franchise lineage.'}
function stats(){let b=byI(),v=viable(),p=prog(),comb=v.filter(i=>(p.solved[i]||[]).length).length,fp=Object.values(p.solved).reduce((a,x)=>a+x.length,0),total=pool().length;$('comboPct').textContent=(v.length?Math.round(comb/v.length*100):0)+'%';$('comboSmall').textContent=comb+'/'+v.length+' combos started';$('playerPct').textContent=(total?Math.round(fp/total*100):0)+'%';$('playerSmall').textContent=fp+'/'+total+' players named'}
function counts(){let arr=byI()[current]||[],f=found(current).length,t=arr.length;$('possible').textContent=t+' possible '+meta().short+' player'+(t===1?'':'s');$('found').textContent=f+' of '+t+' named · '+(t?Math.round(f/t*100):0)+'%';$('comboBar').style.width=(t?f/t*100:0)+'%'}
function render(){resetHint();applyTheme();$('subtitle').textContent=meta().name+' · relaxed mode';$('challengeLabel').textContent=meta().name;$('guessLabel').textContent='Name a '+meta().short+' player';$('initials').textContent=current;counts();stats();updateEra();document.querySelectorAll('[data-scope]').forEach(b=>b.classList.toggle('active',b.dataset.scope===cfg.scope));document.querySelectorAll('[data-era]').forEach(b=>b.classList.toggle('active',b.dataset.era===cfg.era));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===cfg.mode));$('message').textContent='';$('hint').hidden=true;$('guess').value=''}
function norm(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}function check(){let q=$('guess').value.trim();if(!q)return;let arr=byI()[current]||[],p=arr.find(x=>norm(x.n)===norm(q));if(!p){$('message').textContent='Not one we have for '+current+' in this challenge.';return}let pr=prog();if((pr.solved[current]||[]).includes(p.id)){$('message').textContent='You already named '+p.n+'.';return}if((pr.revealed[current]||[]).includes(p.id)){$('message').textContent=p.n+' was already revealed, so it cannot count toward Players Named.';return}(pr.solved[current]??=[]).push(p.id);put(pr);resetHint();$('hint').hidden=true;$('guess').value='';counts();stats();let remaining=arr.filter(x=>!(pr.solved[current]||[]).includes(x.id)&&!(pr.revealed[current]||[]).includes(x.id)).length;if(remaining)$('message').textContent='✓ '+p.n+' — '+remaining+' more unrevealed answer'+(remaining===1?'':'s')+' for '+current+'.';else{$('message').textContent='✓ '+p.n+' — challenge cleared!';setTimeout(advance,1400)}}
function target(){let pr=prog(),r=(byI()[current]||[]).filter(p=>!(pr.solved[current]||[]).includes(p.id)&&!(pr.revealed[current]||[]).includes(p.id));if(!r.length)return null;let p=r.find(x=>x.id===hintPlayerId)||r[Math.floor(Math.random()*r.length)];hintPlayerId=p.id;return p}function eraName(p){let y=teamYears(p);if(y[0]<=1999&&y[1]>=2000)return'Classic / Modern';if(y[1]<=1999)return'Classic';if(y[1]>=CURRENT-RECENT+1)return'Current / Modern';return'Modern'}function otherTeams(p){let excluded=cfg.scope==='team'?[cfg.choice]:cfg.scope==='region'?['CHC','CHW']:[];return p.career.filter(x=>!excluded.includes(x)).map(x=>MLB[x]?.name).filter(Boolean)}
function hint(){let p=target(),box=$('hint');box.hidden=false;if(!p){box.innerHTML='No unrevealed players remain for this combination.';return}if(hintLevel<4)hintLevel++;let y=teamYears(p),lines=[];if(hintLevel>=1)lines.push(`<div class="hintLine"><strong>Position:</strong> ${p.p||'Unknown'}</div>`);if(hintLevel>=2)lines.push(`<div class="hintLine"><strong>Era:</strong> ${eraName(p)}</div>`);let oth=otherTeams(p);if(hintLevel>=3)lines.push(`<div class="hintLine"><strong>Other teams:</strong> ${oth.length?oth.slice(0,5).join(', '):'No other current-franchise lineage'}</div>`);if(hintLevel>=4)lines.push(`<div class="hintLine"><strong>${meta().short} years:</strong> ${y[0]}${y[1]!==y[0]?'–'+y[1]:''}</div>`);let c=hintLevel<4?'':`<div class="hintWarning"><strong>Strong hint ahead</strong><div>The next clue reveals this player's first name.</div><button id="firstNameHint" class="ghost hintStrong">⚠️ Reveal First Name</button></div>`;box.innerHTML=`<div class="hintTitle">Hints for one remaining ${current} player</div>`+lines.join('')+c;if(hintLevel>=4)$('firstNameHint').onclick=firstName}
function firstName(){let p=target(),y=teamYears(p);firstNameShown=true;$('hint').innerHTML=`<div class="hintTitle">Same mystery player</div><div class="hintLine"><strong>Position:</strong> ${p.p||'Unknown'}</div><div class="hintLine"><strong>${meta().short} years:</strong> ${y[0]}${y[1]!==y[0]?'–'+y[1]:''}</div><div class="hintLine"><strong>First name:</strong> ${p.n.split(/\s+/)[0]}</div><div class="hintWarning"><strong>Still stuck?</strong><div>Revealing the full player will permanently make this answer ineligible for Players Named in this challenge.</div><button id="revealPlayer" class="ghost hintStrong">🏳️ Reveal Player</button></div>`;$('revealPlayer').onclick=revealPlayer}
function revealPlayer(){let p=target(),pr=prog();(pr.revealed[current]??=[]).push(p.id);put(pr);$('hint').innerHTML=`<div class="hintTitle">Revealed player</div><div class="revealed">${p.n}</div><div class="revealNote">This answer cannot count toward Players Named for this challenge.</div>`;counts();stats()}
function defer(){let pr=prog();if(!pr.deferred.includes(current))pr.deferred.push(current);put(pr);advance()}function jump(){let t=$('firstLetter').value+$('lastLetter').value,b=byI();if(!b[t]?.length)return alert('No qualifying players for '+t+' in this challenge.');current=t;let s=seq(),n=s.indexOf(t);if(n>=0)idx=n;render();$('settingsModal').hidden=true}
for(let id of ['firstLetter','lastLetter'])for(let l of L){let o=document.createElement('option');o.value=o.textContent=l;$(id).appendChild(o)}$('firstLetter').value='N';$('lastLetter').value='S';$('jumpBtn').onclick=jump;$('submit').onclick=check;$('hintBtn').onclick=hint;$('later').onclick=defer;$('guess').onkeydown=e=>{if(e.key==='Enter')check()};document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>setScope(b.dataset.scope));document.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>setEra(b.dataset.era));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('settingsBtn').onclick=()=>$('settingsModal').hidden=false;$('closeSettings').onclick=()=>$('settingsModal').hidden=true;$('resetReveal').onclick=()=>$('resetConfirm').hidden=false;$('cancelReset').onclick=()=>$('resetConfirm').hidden=true;$('reset').onclick=()=>{localStorage.removeItem(key());location.reload()};$('settingsModal').onclick=e=>{if(e.target===$('settingsModal'))$('settingsModal').hidden=true};buildChoices();pick();
