const PLAYERS=window.ATHLETE_PLAYERS||[], MLB=window.MLB_TEAMS||{};const CURRENT=2026,RECENT=6,L='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),ALL=L.flatMap(a=>L.map(b=>a+b)),DOUB=L.map(x=>x+x);

const TEAM_THEMES={
ANA:['#080b10','#121820','#19212b','#ba0021','#ffffff','#171d25','#0b162a'],
ARI:['#080b0e','#15191e','#20262d','#a71930','#ffffff','#1b2026','#e3d4ad'],
ATL:['#080b10','#111923','#182332','#ce1141','#ffffff','#17212d','#0c2340'],
BAL:['#080b0e','#14171b','#1d2126','#df4601','#ffffff','#191c20','#000000'],
BOS:['#080b10','#111923','#182332','#bd3039','#ffffff','#17212d','#0c2340'],
CHC:['#080b10','#111923','#182332','#0e3386','#ffffff','#17212d','#cc3433'],
CHW:['#080b0e','#14171a','#1d2125','#c4ced4','#080b0e','#191d21','#ffffff'],
CIN:['#080b0e','#15181c','#1e2227','#c6011f','#ffffff','#1a1e22','#000000'],
CLE:['#080b10','#111923','#182332','#e31937','#ffffff','#17212d','#0c2340'],
COL:['#090a0f','#17151d','#211e29','#6f42a1','#ffffff','#1d1a24','#c4ced4'],
DET:['#080b10','#111923','#182332','#0c2340','#ffffff','#17212d','#fa4616'],
FLA:['#080b0e','#13191c','#1b2428','#00a3e0','#ffffff','#182125','#ef3340'],
HOU:['#080b10','#111923','#182332','#eb6e1f','#ffffff','#17212d','#002d62'],
KCR:['#080b10','#111923','#182332','#004687','#ffffff','#17212d','#7ab2dd'],
LAD:['#080b10','#111923','#182332','#005a9c','#ffffff','#17212d','#ffffff'],
MIL:['#080b10','#121923','#192332','#ffc52f','#12284b','#17212d','#12284b'],
MIN:['#080b10','#111923','#182332','#d31145','#ffffff','#17212d','#002b5c'],
NYM:['#080b10','#111923','#182332','#ff5910','#ffffff','#17212d','#002d72'],
NYY:['#080b10','#111923','#182332','#0c2340','#ffffff','#17212d','#c4ced4'],
OAK:['#080d0b','#111c18','#182720','#efb21e','#10261d','#17231e','#003831'],
PHI:['#080b10','#111923','#182332','#e81828','#ffffff','#17212d','#003087'],
PIT:['#080b0e','#15191e','#20262d','#fdb827','#16130a','#1b2026','#000000'],
SDP:['#0b0907','#18140f','#231d16','#ffc425','#20180c','#1f1913','#2f241d'],
SEA:['#080b10','#111923','#182332','#005c5c','#ffffff','#17212d','#c4ced4'],
SFG:['#080b0e','#15191e','#20262d','#fd5a1e','#ffffff','#1b2026','#000000'],
STL:['#080b10','#111923','#182332','#c41e3a','#ffffff','#17212d','#0c2340'],
TBD:['#080b10','#111923','#182332','#8fbce6','#092c5c','#17212d','#f5d130'],
TEX:['#080b10','#111923','#182332','#c0111f','#ffffff','#17212d','#003278'],
TOR:['#080b10','#111923','#182332','#134a8e','#ffffff','#17212d','#e8291c'],
WSN:['#080b10','#111923','#182332','#ab0003','#ffffff','#17212d','#14225a']
 };

const NBA_TEAM_THEMES={CHI:['#080b10','#171219','#241c22','#CE1141','#ffffff','#21171c','#000000'],BOS:['#080d0b','#111c18','#182720','#007A33','#ffffff','#17231e','#BA9653'],LAL:['#0a0810','#17131e','#211b2a','#FDB927','#271047','#1d1825','#552583'],GSW:['#080b10','#111923','#182332','#FFC72C','#1D428A','#17212d','#1D428A'],NYK:['#080b10','#111923','#182332','#F58426','#ffffff','#17212d','#006BB6'],MIA:['#080b0e','#15191e','#20262d','#98002E','#ffffff','#1b2026','#F9A01B'],MIL:['#080d0b','#111c18','#182720','#00471B','#ffffff','#17231e','#EEE1C6'],DEN:['#080b10','#111923','#182332','#FEC524','#0E2240','#17212d','#0E2240'],CLE:['#0b0907','#18140f','#231d16','#FFB81C','#291B36','#1f1913','#6F263D'],DAL:['#080b10','#111923','#182332','#00538C','#ffffff','#17212d','#B8C4CA'],PHI:['#080b10','#111923','#182332','#ED174C','#ffffff','#17212d','#006BB6'],SAS:['#080b0e','#14171a','#1d2125','#C4CED4','#101010','#191d21','#ffffff']};
const NHL_TEAM_THEMES={SJS:['#071518','#10262b','#18343a','#006D75','#ffffff','#163238','#E57200'],CHI:['#080b0e','#16151b','#24212a','#CF0A2C','#ffffff','#211b24','#ffffff'],BOS:['#080b0e','#1b1812','#292418','#FFB81C','#121212','#221f18','#ffffff'],DET:['#080b0e','#1c1518','#281c20','#CE1126','#ffffff','#221a1e','#ffffff'],NYR:['#080b10','#111923','#182332','#005DAA','#ffffff','#17212d','#ffffff'],MTL:['#080b10','#151821','#21202b','#AF1E2D','#ffffff','#1b1b25','#ffffff'],TOR:['#080b10','#111923','#182332','#00205B','#ffffff','#17212d','#ffffff'],PIT:['#080b0e','#1b1812','#292418','#FCB514','#121212','#221f18','#ffffff'],STL:['#080b10','#111923','#182332','#FCB514','#002F87','#17212d','#ffffff'],COL:['#080b10','#151821','#21202b','#6F263D','#ffffff','#1b1b25','#ffffff'],VGK:['#080b0e','#1b1812','#292418','#B4975A','#121212','#221f18','#ffffff']};
const NFL_TEAM_THEMES={
ARI:['#080b0e','#15191e','#20262d','#97233F','#ffffff','#1b2026','#FFB612'],ATL:['#080b0e','#15191e','#20262d','#A71930','#ffffff','#1b2026','#000000'],BAL:['#09080d','#17141d','#211d29','#9E7C0C','#ffffff','#1d1924','#241773'],BUF:['#080b10','#111923','#182332','#00338D','#ffffff','#17212d','#C60C30'],CAR:['#080b0e','#14191d','#1c2328','#0085CA','#ffffff','#182125','#101820'],CHI:['#080b10','#111923','#182332','#C83803','#ffffff','#17212d','#0B162A'],CIN:['#080b0e','#15191e','#20262d','#FB4F14','#ffffff','#1b2026','#000000'],CLE:['#0b0907','#18140f','#231d16','#FF3C00','#ffffff','#1f1913','#311D00'],DAL:['#080b10','#111923','#182332','#003594','#ffffff','#17212d','#869397'],DEN:['#080b10','#111923','#182332','#FB4F14','#ffffff','#17212d','#002244'],DET:['#080b10','#111923','#182332','#0076B6','#ffffff','#17212d','#B0B7BC'],GB:['#080d0b','#111c18','#182720','#FFB612','#203731','#17231e','#203731'],HOU:['#080b10','#111923','#182332','#03202F','#ffffff','#17212d','#A71930'],IND:['#080b10','#111923','#182332','#002C5F','#ffffff','#17212d','#A2AAAD'],JAX:['#080d0d','#111b1b','#182626','#00A5B5','#ffffff','#172222','#D7A22A'],KC:['#080b0e','#15191e','#20262d','#E31837','#ffffff','#1b2026','#FFB81C'],LV:['#080b0e','#14171a','#1d2125','#A5ACAF','#080b0e','#191d21','#ffffff'],LAC:['#080b10','#111923','#182332','#0080C6','#ffffff','#17212d','#FFC20E'],LAR:['#080b10','#111923','#182332','#003594','#ffffff','#17212d','#FFA300'],MIA:['#080d0d','#111b1b','#182626','#008E97','#ffffff','#172222','#FC4C02'],MIN:['#0a0810','#17131e','#211b2a','#4F2683','#ffffff','#1d1825','#FFC62F'],NE:['#080b10','#111923','#182332','#002244','#ffffff','#17212d','#C60C30'],NO:['#0b0a07','#18160f','#231f16','#D3BC8D','#10100d','#1f1b13','#101820'],NYG:['#080b10','#111923','#182332','#0B2265','#ffffff','#17212d','#A71930'],NYJ:['#080d0b','#111c18','#182720','#125740','#ffffff','#17231e','#ffffff'],PHI:['#080d0d','#111b1b','#182626','#004C54','#ffffff','#172222','#A5ACAF'],PIT:['#080b0e','#15191e','#20262d','#FFB612','#15130a','#1b2026','#000000'],SEA:['#080b10','#111923','#182332','#69BE28','#0b162a','#17212d','#002244'],SF:['#080b0e','#15191e','#20262d','#AA0000','#ffffff','#1b2026','#B3995D'],TB:['#080b0e','#15191e','#20262d','#D50A0A','#ffffff','#1b2026','#34302B'],TEN:['#080b10','#111923','#182332','#4B92DB','#ffffff','#17212d','#0C2340'],WAS:['#0b0908','#181310','#231c17','#5A1414','#ffffff','#1f1814','#FFB612']
};

const REGIONS={
 arizona:{name:'Arizona',teams:['ARI']}, atlanta:{name:'Atlanta',teams:['ATL']}, baltimore:{name:'Baltimore',teams:['BAL']},
 boston:{name:'Boston / New England',teams:['BOS']}, chicago:{name:'Chicago',teams:['CHC','CHW']}, cincinnati:{name:'Cincinnati',teams:['CIN']},
 cleveland:{name:'Cleveland',teams:['CLE']}, colorado:{name:'Colorado',teams:['COL']}, detroit:{name:'Detroit',teams:['DET']},
 houston:{name:'Houston',teams:['HOU']}, kansascity:{name:'Kansas City',teams:['KCR']}, losangeles:{name:'Los Angeles',teams:['LAD','ANA']},
 miami:{name:'Miami / South Florida',teams:['FLA']}, minnesota:{name:'Minnesota',teams:['MIN']}, newyork:{name:'New York',teams:['NYY','NYM']},
 philadelphia:{name:'Philadelphia',teams:['PHI']}, pittsburgh:{name:'Pittsburgh',teams:['PIT']}, sandiego:{name:'San Diego',teams:['SDP']},
 bayarea:{name:'San Francisco Bay Area',teams:['SFG']}, sacramento:{name:'Sacramento',teams:['OAK']}, seattle:{name:'Seattle',teams:['SEA']},
 stlouis:{name:'St. Louis',teams:['STL']}, tampabay:{name:'Tampa Bay',teams:['TBD']}, dallasfortworth:{name:'Dallas–Fort Worth',teams:['TEX']},
 toronto:{name:'Toronto',teams:['TOR']}, washington:{name:'Washington, DC',teams:['WSN']}, wisconsin:{name:'Wisconsin',teams:['MIL']}
};
// Historical location windows for relocated MLB franchise lineages. Region eligibility follows where the club played in that season.
const REGION_WINDOWS={
 atlanta:[['ATL',1966,2026]], boston:[['BOS',1901,2026],['ATL',1876,1952]], wisconsin:[['MIL',1970,2026],['ATL',1953,1965]],
 newyork:[['NYY',1903,2026],['NYM',1962,2026],['LAD',1884,1957],['SFG',1883,1957]],
 losangeles:[['LAD',1958,2026],['ANA',1961,2026]], bayarea:[['SFG',1958,2026],['OAK',1968,2024]], sacramento:[['OAK',2025,2026]],
 philadelphia:[['PHI',1883,2026],['OAK',1901,1954]], kansascity:[['KCR',1969,2026],['OAK',1955,1967]],
 minnesota:[['MIN',1961,2026]], washington:[['WSN',2005,2026],['MIN',1901,1960],['TEX',1961,1971]], dallasfortworth:[['TEX',1972,2026]],
 baltimore:[['BAL',1954,2026]], stlouis:[['STL',1882,2026],['BAL',1902,1953]],
 arizona:[['ARI',1998,2026]], chicago:[['CHC',1876,2026],['CHW',1901,2026]], cincinnati:[['CIN',1882,2026]], cleveland:[['CLE',1901,2026]],
 colorado:[['COL',1993,2026]], detroit:[['DET',1901,2026]], houston:[['HOU',1962,2026]], miami:[['FLA',1993,2026]],
 pittsburgh:[['PIT',1882,2026]], sandiego:[['SDP',1969,2026]], seattle:[['SEA',1977,2026]], tampabay:[['TBD',1998,2026]], toronto:[['TOR',1977,2026]]
};
function applyTheme(){
 const root=document.documentElement,m=meta();
 document.body.className='theme-'+m.theme;
 if(cfg.scope==='team'){
   const t=(cfg.sport==='NFL'?NFL_TEAM_THEMES[cfg.choice]:cfg.sport==='NBA'?(NBA_TEAM_THEMES[cfg.choice]||TEAM_THEMES[cfg.choice]):cfg.sport==='NHL'?(NHL_TEAM_THEMES[cfg.choice]||TEAM_THEMES[cfg.choice]):TEAM_THEMES[cfg.choice])||(cfg.sport==='NFL'?NFL_TEAM_THEMES.CHI:cfg.sport==='NBA'?NBA_TEAM_THEMES.CHI:cfg.sport==='NHL'?NHL_TEAM_THEMES.CHI:TEAM_THEMES.CHW);
   ['--bg','--panel','--panel2','--accent','--accentInk','--soft','--secondary'].forEach((v,i)=>{root.style.setProperty(v,t[i]);document.body.style.setProperty(v,t[i])});
   root.style.setProperty('--line',t[2]);
   document.body.style.setProperty('--line',t[2]);
 }else{
   ['--bg','--panel','--panel2','--accent','--accentInk','--soft','--secondary','--line'].forEach(v=>{root.style.removeProperty(v);document.body.style.removeProperty(v)});
 }
}


const NFL_TEAMS={
ARI:{name:'Arizona Cardinals',short:'Cardinals',first:1920},ATL:{name:'Atlanta Falcons',short:'Falcons',first:1966},BAL:{name:'Baltimore Ravens',short:'Ravens',first:1996},BUF:{name:'Buffalo Bills',short:'Bills',first:1960},CAR:{name:'Carolina Panthers',short:'Panthers',first:1995},CHI:{name:'Chicago Bears',short:'Bears',first:1920},CIN:{name:'Cincinnati Bengals',short:'Bengals',first:1968},CLE:{name:'Cleveland Browns',short:'Browns',first:1946},DAL:{name:'Dallas Cowboys',short:'Cowboys',first:1960},DEN:{name:'Denver Broncos',short:'Broncos',first:1960},DET:{name:'Detroit Lions',short:'Lions',first:1930},GB:{name:'Green Bay Packers',short:'Packers',first:1921},HOU:{name:'Houston Texans',short:'Texans',first:2002},IND:{name:'Indianapolis Colts',short:'Colts',first:1953},JAX:{name:'Jacksonville Jaguars',short:'Jaguars',first:1995},KC:{name:'Kansas City Chiefs',short:'Chiefs',first:1960},LV:{name:'Las Vegas Raiders',short:'Raiders',first:1960},LAC:{name:'Los Angeles Chargers',short:'Chargers',first:1960},LAR:{name:'Los Angeles Rams',short:'Rams',first:1937},MIA:{name:'Miami Dolphins',short:'Dolphins',first:1966},MIN:{name:'Minnesota Vikings',short:'Vikings',first:1961},NE:{name:'New England Patriots',short:'Patriots',first:1960},NO:{name:'New Orleans Saints',short:'Saints',first:1967},NYG:{name:'New York Giants',short:'Giants',first:1925},NYJ:{name:'New York Jets',short:'Jets',first:1960},PHI:{name:'Philadelphia Eagles',short:'Eagles',first:1933},PIT:{name:'Pittsburgh Steelers',short:'Steelers',first:1933},SEA:{name:'Seattle Seahawks',short:'Seahawks',first:1976},SF:{name:'San Francisco 49ers',short:'49ers',first:1946},TB:{name:'Tampa Bay Buccaneers',short:'Buccaneers',first:1976},TEN:{name:'Tennessee Titans',short:'Titans',first:1960},WAS:{name:'Washington Commanders',short:'Commanders',first:1932}
};
const NFL_FRANCHISE=Object.fromEntries(Object.keys(NFL_TEAMS).map(t=>[t,[[t,1920,2026]]]));
const NFL_REGION_WINDOWS={
arizona:[['ARI',1988,2026]],atlanta:[['ATL',1966,2026]],baltimore:[['IND',1953,1983],['BAL',1996,2026]],boston:[['NE',1960,2026]],buffalo:[['BUF',1960,2026]],carolina:[['CAR',1995,2026]],chicago:[['CHI',1920,2026],['ARI',1920,1959],['HIST_CHT',1920,1920]],cincinnati:[['CIN',1968,2026]],cleveland:[['CLE',1946,1995],['CLE',1999,2026],['LAR',1937,1945]],colorado:[['DEN',1960,2026]],dallasfortworth:[['DAL',1960,2026]],detroit:[['DET',1930,2026]],houston:[['TEN',1960,1996],['HOU',2002,2026]],indiana:[['IND',1984,2026]],jacksonville:[['JAX',1995,2026]],kansascity:[['KC',1963,2026]],lasvegas:[['LV',2020,2026]],losangeles:[['LAR',1946,1994],['LAR',2016,2026],['LV',1982,1994],['LAC',1960,1960],['LAC',2017,2026]],miami:[['MIA',1966,2026]],minnesota:[['MIN',1961,2026]],nashville:[['TEN',1997,2026]],neworleans:[['NO',1967,2026]],newyork:[['NYG',1925,2026],['NYJ',1960,2026]],philadelphia:[['PHI',1933,2026]],pittsburgh:[['PIT',1933,2026]],sandiego:[['LAC',1961,2016]],bayarea:[['SF',1946,2026],['LV',1960,1981],['LV',1995,2019]],seattle:[['SEA',1976,2026]],stlouis:[['ARI',1960,1987],['LAR',1995,2015]],tampabay:[['TB',1976,2026]],washington:[['WAS',1937,2026]],wisconsin:[['GB',1921,2026]]};
const EXTRA_REGIONS={buffalo:{name:'Buffalo'},carolina:{name:'Carolina'},indiana:{name:'Indiana'},jacksonville:{name:'Jacksonville'},lasvegas:{name:'Las Vegas'},nashville:{name:'Nashville'},neworleans:{name:'New Orleans'}};Object.assign(REGIONS,EXTRA_REGIONS);
Object.assign(REGIONS,{montreal:{name:'Montreal'},ottawa:{name:'Ottawa'},calgary:{name:'Calgary'},edmonton:{name:'Edmonton'},winnipeg:{name:'Winnipeg'},quebec:{name:'Quebec'},newjersey:{name:'New Jersey'},anaheim:{name:'Anaheim'},columbus:{name:'Columbus'},portland:{name:'Portland'},oklahomacity:{name:'Oklahoma City'},memphis:{name:'Memphis'},orlando:{name:'Orlando'},saltlake:{name:'Utah'},vancouver:{name:'Vancouver'},kentucky:{name:'Kentucky'},virginia:{name:'Virginia'},rochester:{name:'Rochester'},syracuse:{name:'Syracuse'},providence:{name:'Providence'},waterloo:{name:'Waterloo'},anderson:{name:'Anderson'}});
const LEGACY={whitesox:'CHW',cubs:'CHC',chicago:'chicago'};let cfg=JSON.parse(localStorage.getItem('aa-v40-config')||localStorage.getItem('aa-v33-config')||localStorage.getItem('aa-v31-config')||localStorage.getItem('aa-v30-config')||'{"sport":"MLB","scope":"team","choice":"CHW","era":"modern","mode":"alphabet"}');cfg.sport=cfg.sport||'MLB';cfg.choice=LEGACY[cfg.choice]||cfg.choice;if(cfg.scope==='league')cfg.choice=cfg.sport;
let current='AA',idx=0,lastRandom=null,hintLevel=0,hintPlayerId=null,firstNameShown=false,namedOpen=false;const $=x=>document.getElementById(x);
const NAMED_KEY='aa-v33-named-athletes',REVEALED_KEY='aa-v33-revealed-contexts',MIGRATED_KEY='aa-v33-migrated';
function readJSON(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function namedSet(){return sharedNamedSet()}
function rawNamedSet(){return new Set(readJSON(NAMED_KEY,[]))}function putNamed(s){localStorage.setItem(NAMED_KEY,JSON.stringify([...s]))}
function revealMap(){return readJSON(REVEALED_KEY,{})}function putReveal(r){localStorage.setItem(REVEALED_KEY,JSON.stringify(r))}
function contextKey(){return cfg.sport==='MLB'?`${cfg.scope}:${cfg.choice}:${cfg.era}:${current}`:`${cfg.sport}:${cfg.scope}:${cfg.choice}:${cfg.era}:${current}`}
function isRevealed(id){return (revealMap()[contextKey()]||[]).includes(id)}
function migrateProgress(){if(localStorage.getItem(MIGRATED_KEY))return;let named=namedSet(),reveals=revealMap();for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(!k||!k.startsWith('aa-v31:'))continue;let pr=readJSON(k,null);if(!pr)continue;Object.values(pr.solved||{}).flat().forEach(id=>named.add(id));let parts=k.split(':');let scope=parts[1],choice=parts[2],era=parts[3];for(let [initial,ids] of Object.entries(pr.revealed||{})){let ck=`MLB:${scope}:${choice}:${era}:${initial}`;reveals[ck]=[...new Set([...(reveals[ck]||[]),...ids])]}}putNamed(named);putReveal(reveals);localStorage.setItem(MIGRATED_KEY,'1')}
function saveCfg(){localStorage.setItem('aa-v40-config',JSON.stringify(cfg))}
// V4.4.1: saved IDs stay untouched. Verified multi-sport identities share progress by ID.
// Only explicitly confirmed cross-league identities are linked: a matching name alone
// can refer to different people (e.g. Will Smith), so it is not safe to auto-merge.
const CROSS_SPORT_NAMES=new Set(['bo jackson','deion sanders','brian jordan','drew henson','chad hutchinson','dave winfield','danny ainge','charlie ward','john elway','kyler murray','tom glavine','michael jordan']);
function cleanPerson(n){return n.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function sportLists(){return [['MLB',PLAYERS],['NFL',window.NFL_PLAYERS||[]],['NBA',window.NBA_PLAYERS||[]],['NHL',window.NHL_PLAYERS||[]]]}
let sharedCache=null,sharedSize=-1;
function sharedIndex(){let lists=sportLists(),size=lists.reduce((a,x)=>a+x[1].length,0);if(sharedCache&&sharedSize===size)return sharedCache;
 const groups=new Map(),byId=new Map(),unified=[];
 for(const [sport,list] of lists)for(const p of list){
  const name=(p.n||'').toLowerCase().replace(/\s+(jr\.?|sr\.?|ii|iii|iv)$/,'').trim();
  const key=CROSS_SPORT_NAMES.has(name)?cleanPerson(name):sport+':'+p.id;
  if(!groups.has(key))groups.set(key,[]);groups.get(key).push({...p,sport});
 }
 for(const group of groups.values()){
  const ids=group.map(p=>p.id),primary=group[0];
  for(const p of group)byId.set(p.id,ids);
  const allYears=group.flatMap(p=>Object.values(p.teams||{}));
  const start=allYears.length?Math.min(...allYears.map(y=>y[0])):0;
  const end=allYears.length?Math.max(...allYears.map(y=>y[1])):0;
  unified.push({...primary,allIds:ids,sourceSports:[...new Set(group.map(p=>p.sport))],teams:{ALL:[start,end]},career:group.map(p=>p.sport),p:group.map(p=>p.sport+' '+(p.p||'')).join(' / ')});
 }
 sharedCache={byId,unified};sharedSize=size;return sharedCache;
}
function sharedNamedSet(){const raw=rawNamedSet(),result=new Set(raw),map=sharedIndex().byId;for(const id of raw)for(const linked of (map.get(id)||[]))result.add(linked);return result}
function players(){return cfg.sport==='ALL'?sharedIndex().unified:cfg.sport==='NFL'?(window.NFL_PLAYERS||[]):cfg.sport==='NBA'?(window.NBA_PLAYERS||[]):cfg.sport==='NHL'?(window.NHL_PLAYERS||[]):PLAYERS}
// V4.2.2: BAA and NBA entries spanning the 1949 league transition are one team.
// Distinct clubs sharing a name retain their own labeled selection.
const NBA_TEAM_ALIASES={NBA_CHS:'BAA_CHS',NBA_STB:'BAA_STB',NBA_WSC:'BAA_WSC',NBA_BLB:'BAA_BLB'};
function nbaChoiceKey(k){return cfg.sport==='NBA'&&cfg.scope==='team'?(NBA_TEAM_ALIASES[k]||k):k}
function nbaTeamChoices(){
 const book=window.NBA_TEAMS||{};
 // Merge only once per page load, not every time the dropdown is rebuilt.
 return Object.entries(book).filter(([k])=>!NBA_TEAM_ALIASES[k]).map(([k,v])=>{
   let name=v.name;
   if(k==='NBA_DNN')name+=' (1949–50)';
   if(k==='ABA_WSA')name+=' (ABA, 1970)';
   return[k,name];
 });
}
let nbaMerged=false;
function ensureNBAChoices(){if(nbaMerged)return;nbaMerged=true;const fr=window.NBA_FRANCHISE||{};for(const [alias,canonical] of Object.entries(NBA_TEAM_ALIASES)){if(fr[alias]&&fr[canonical])fr[canonical]=[...fr[canonical],...fr[alias]]}}
function teamBook(){return cfg.sport==='NFL'?NFL_TEAMS:cfg.sport==='NBA'?window.NBA_TEAMS:cfg.sport==='NHL'?window.NHL_TEAMS:MLB}
function regionWindows(){return cfg.sport==='NFL'?NFL_REGION_WINDOWS:cfg.sport==='NBA'?window.NBA_REGION_WINDOWS:cfg.sport==='NHL'?window.NHL_REGION_WINDOWS:REGION_WINDOWS}
function meta(){if(cfg.sport==='ALL')return{name:'All Sports · MLB + NFL + NBA + NHL',short:'All Sports',first:1871,theme:'all'};if(cfg.scope==='league')return{name:cfg.sport==='NFL'?'National Football League':cfg.sport==='NBA'?'NBA · ABA · BAA':cfg.sport==='NHL'?'National Hockey League':'Major League Baseball',short:cfg.sport,first:cfg.sport==='NFL'?1920:cfg.sport==='NBA'?1947:cfg.sport==='NHL'?1918:1871,theme:cfg.sport.toLowerCase()};if(cfg.scope==='region'){let r=REGIONS[cfg.choice]||REGIONS.chicago,w=regionWindows()[cfg.choice]||[];return{name:r.name+' Region · '+cfg.sport,short:r.name+' '+cfg.sport,first:w.length?Math.min(...w.map(x=>x[1])):(cfg.sport==='NFL'?1920:cfg.sport==='NBA'?1947:cfg.sport==='NHL'?1918:1871),theme:'region'}}let m=teamBook()[cfg.choice]||Object.values(teamBook())[0];return{name:m.name,short:m.short,first:cfg.sport==='NHL'?Math.min(m.first,...(window.NHL_FRANCHISE?.[cfg.choice]||[]).map(x=>x[1])):m.first,theme:'team'}}
function windowsForTeam(){return cfg.sport==='NFL'?(NFL_FRANCHISE[cfg.choice]||[]):cfg.sport==='NBA'?(window.NBA_FRANCHISE[cfg.choice]||[]):cfg.sport==='NHL'?(window.NHL_FRANCHISE[cfg.choice]||[]):null}
function teamYears(p){if(cfg.sport==='ALL')return p.teams.ALL||null;if(cfg.scope==='league'){let a=Object.values(p.teams);return a.length?[Math.min(...a.map(x=>x[0])),Math.max(...a.map(x=>x[1]))]:null}let wins=cfg.scope==='region'?(regionWindows()[cfg.choice]||[]):windowsForTeam();if(cfg.sport==='NFL'||cfg.sport==='NBA'||cfg.sport==='NHL'||cfg.scope==='region'){let hits=[];for(let [team,start,end] of (wins||[])){let y=p.teams[team];if(!y)continue;let a=Math.max(y[0],start),b=Math.min(y[1],end);if(a<=b)hits.push([a,b])}return hits.length?[Math.min(...hits.map(x=>x[0])),Math.max(...hits.map(x=>x[1]))]:null}return p.teams[cfg.choice]||null}
function eraRange(e){let f=meta().first;if(cfg.sport==='ALL'){if(e==='current')return[2021,2026];if(e==='modern')return[2000,2026];if(e==='classic')return[1871,1999];return[1871,2026]}if(cfg.sport==='NHL'){if(e==='current')return[2021,2026];if(e==='modern')return[2000,2026];if(e==='classic')return[f,1999];return[f,2026]}if(e==='current')return[Math.max(f,CURRENT-RECENT+1),CURRENT];if(e==='modern')return[Math.max(f,2000),CURRENT];if(e==='classic')return[f,Math.min(1999,CURRENT)];return[f,CURRENT]}
function pool(){let [s,e]=eraRange(cfg.era);if(cfg.sport==='NHL')e=Math.min(e,2026);return players().filter(p=>{let y=teamYears(p);return y&&y[0]<=e&&y[1]>=s})}function byI(){let b={};for(let p of pool())(b[p.i]??=[]).push(p);return b}function found(i){let n=namedSet();return (byI()[i]||[]).filter(p=>n.has(p.id)).map(p=>p.id)}function viable(){let b=byI();return ALL.filter(i=>b[i]?.length)}function seq(){let b=byI();return (cfg.mode==='double'?DOUB:ALL).filter(i=>b[i]?.length)}
function resetHint(){hintLevel=0;hintPlayerId=null;firstNameShown=false}function pick(){resetHint();let b=byI(),v=viable();if(!v.length){current='AA';render();return}if(cfg.mode==='random'){let q=v.filter(i=>found(i).length<(b[i]?.length||0)&&i!==lastRandom);if(!q.length)q=v.filter(i=>i!==lastRandom);current=q[Math.floor(Math.random()*q.length)]||v[0]}else{let ss=seq();current=ss[idx%ss.length]||v[0]}lastRandom=current;render()}
async function setSport(s){if(s===cfg.sport)return;cfg.sport=s;cfg.scope=s==='ALL'?'league':'team';cfg.choice=s==='ALL'?'ALL':['NFL','NBA','NHL'].includes(s)?'CHI':'CHW';cfg.era=['NFL','NBA','NHL'].includes(s)?'all':cfg.era;saveCfg();idx=0;if((s==='NFL'||s==='ALL')&&!(window.NFL_PLAYERS||[]).length){$('dataStatus').textContent='Loading NFL history for the first time…';document.body.classList.add('loading');try{await window.loadNFLPlayers();$('dataStatus').textContent='NFL historical rosters are built into V4.4.'}catch(e){$('dataStatus').textContent='NFL data could not load. Check your connection and try again.';console.error(e)}document.body.classList.remove('loading')}buildChoices();pick()}
function setScope(x){if(cfg.sport==='ALL')return;cfg.scope=x;cfg.choice=x==='region'?'chicago':x==='league'?cfg.sport:(['NFL','NBA','NHL'].includes(cfg.sport)?'CHI':'CHW');saveCfg();idx=0;buildChoices();pick()}function setChoice(c){cfg.choice=c;saveCfg();idx=0;buildChoices();pick()}function setEra(e){cfg.era=e;saveCfg();idx=0;pick()}function setMode(m){cfg.mode=m;saveCfg();idx=0;pick()}function advance(){if(cfg.mode==='random')pick();else{idx++;pick()}}
function years(r){return r[0]+'–'+String(r[1]).slice(-2)}function updateEra(){for(let e of ['current','modern','classic','all'])$(e+'Years').textContent=years(eraRange(e));let r=eraRange(cfg.era);$('eraNote').textContent=`${r[0]}–${r[1]}: a player qualifies if any ${meta().short} season overlaps this range.`}
function buildChoices(){if(cfg.sport==='ALL'){cfg.scope='league';cfg.choice='ALL';document.querySelectorAll('[data-scope]').forEach(b=>{b.disabled=b.dataset.scope!=='league'});}else document.querySelectorAll('[data-scope]').forEach(b=>b.disabled=false);let box=$('scopeChoices');box.innerHTML='';let cs=[];if(cfg.scope==='region'){let rw=regionWindows();cs=Object.entries(REGIONS).filter(([k])=>rw[k]?.length).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([k,v])=>[k,v.name])}else if(cfg.scope==='team'){if(cfg.sport==='NBA'){ensureNBAChoices();cfg.choice=nbaChoiceKey(cfg.choice);cs=nbaTeamChoices()}else if(cfg.sport==='NHL'){const hidden=new Set(['CBH','DTC','DTF','TRS','TRA','MNS','ATF','QUE','KCS','CLR','PHX','HAR','MDA','WIN']);cs=Object.entries(teamBook()).filter(([k])=>!hidden.has(k)).map(([k,v])=>[k,v.name]);}else cs=Object.entries(teamBook()).map(([k,v])=>[k,v.name]);cs.sort((a,b)=>a[1].localeCompare(b[1]))}else cs=[[cfg.sport,cfg.sport==='ALL'?'Every athlete across all four sports':'All '+cfg.sport+' franchises']];if(!cs.some(x=>x[0]===cfg.choice)){cfg.choice=cfg.scope==='region'?'chicago':cfg.scope==='league'?cfg.sport:(['NFL','NBA','NHL'].includes(cfg.sport)?'CHI':'CHW');saveCfg()}if(cfg.scope==='team'||cfg.scope==='region'){let label=document.createElement('label');label.className='choiceLabel';label.htmlFor='scopeSelect';label.textContent=cfg.scope==='team'?'Team':'Region';let sel=document.createElement('select');sel.id='scopeSelect';sel.className='scopeSelect';for(let [k,n] of cs){let o=document.createElement('option');o.value=k;o.textContent=n;o.selected=k===cfg.choice;sel.appendChild(o)}sel.onchange=()=>setChoice(sel.value);box.append(label,sel)}else{let summary=document.createElement('div');summary.className='leagueChoice';summary.textContent=cs[0][1];box.appendChild(summary)}$('leagueScopeBtn').textContent=cfg.sport==='ALL'?'All Sports':cfg.sport;$('scopeNote').textContent=cfg.sport==='ALL'?'One shared challenge across MLB, NFL, NBA and NHL. Your existing named athletes count automatically.':cfg.scope==='region'?`Choose a sports region. Historical ${cfg.sport} relocations are assigned to where the club played at the time.`:cfg.scope==='league'?`Any player in the ${cfg.sport} historical database qualifies.`:`Choose a ${cfg.sport} team. Historical names and relocations follow franchise lineage.`}
function pct(n,d){if(!d)return'0%';let x=n/d*100;return (x>0&&x<1?x.toFixed(1):Math.round(x))+'%'}
function stats(){let b=byI(),v=viable(),n=namedSet(),comb=v.filter(i=>(b[i]||[]).some(p=>n.has(p.id))).length,eligible=pool(),fp=eligible.filter(p=>n.has(p.id)).length,total=eligible.length;$('comboPct').textContent=pct(comb,v.length);$('comboSmall').textContent=comb+'/'+v.length+' combos started';$('playerPct').textContent=pct(fp,total);$('playerSmall').textContent=fp+'/'+total+' players named'}
const DISPLAY_OVERRIDES={griffke01:'Ken Griffey Sr.',griffke02:'Ken Griffey Jr.',guerrvl02:'Vladimir Guerrero Jr.'};
function displayName(p){return DISPLAY_OVERRIDES[p.id]||p.n}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function careerRange(p){let a=Object.values(p.teams||{});return a.length?[Math.min(...a.map(x=>x[0])),Math.max(...a.map(x=>x[1]))]:null}
function disambigLabel(p){let r=careerRange(p),debut=r?r[0]:null;return [p.p||'position unknown',debut?('debuted '+debut):''].filter(Boolean).join(' · ')}
function namedPlayersHere(){let n=namedSet();return (byI()[current]||[]).filter(p=>n.has(p.id)).sort((a,b)=>displayName(a).localeCompare(displayName(b)))}
function renderNamed(){let a=namedPlayersHere();$('namedInitials').textContent=current;$('namedCount').textContent=a.length;$('namedToggle').innerHTML=`Players Named for <span id="namedInitials">${current}</span> — <span id="namedCount">${a.length}</span> · ${namedOpen?'Hide players':'Show players'}`;$('namedList').hidden=!namedOpen;$('namedList').innerHTML=a.length?a.map(p=>`<div>${esc(displayName(p))}</div>`).join(''):'<div class="muted">None named yet.</div>'}
function counts(){let arr=byI()[current]||[],f=found(current).length,t=arr.length;$('possible').textContent=t+' possible '+meta().short+' player'+(t===1?'':'s');$('found').textContent=f+' of '+t+' named · '+(t?Math.round(f/t*100):0)+'%';$('comboBar').style.width=(t?f/t*100:0)+'%';renderNamed()}
function render(){resetHint();applyTheme();$('subtitle').textContent=meta().name+' · relaxed mode';$('footerText').textContent=cfg.sport==='ALL'?'Athlete Alphabet V4.4.6 · All Sports · shared progress · knowledge, not speed':cfg.sport==='MLB'?'Athlete Alphabet V4.4.6 · MLB data snapshot: full 2026 regular season · knowledge, not speed':cfg.sport==='NFL'?'Athlete Alphabet V4.4.6 · NFL historical rosters: 1920–2026 · knowledge, not speed':cfg.sport==='NBA'?'Athlete Alphabet V4.4.6 · NBA / ABA / BAA history: 1947–2026 · knowledge, not speed':'Athlete Alphabet V4.4.6 · NHL historical seasons: 1917–18 through 2025–26 · knowledge, not speed';$('challengeLabel').textContent=meta().name;$('guessLabel').textContent=cfg.sport==='ALL'?'Name an athlete from any sport':'Name a '+meta().short+' player';$('initials').textContent=current;counts();stats();updateEra();document.querySelectorAll('[data-sport]').forEach(b=>b.classList.toggle('active',b.dataset.sport===cfg.sport));document.querySelectorAll('[data-scope]').forEach(b=>b.classList.toggle('active',b.dataset.scope===cfg.scope));document.querySelectorAll('[data-era]').forEach(b=>b.classList.toggle('active',b.dataset.era===cfg.era));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===cfg.mode));$('message').textContent='';$('hint').hidden=true;$('guess').value=''}
function norm(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function normAnswer(s){return norm(s.replace(/(?:,?\s+)(?:jr\.?|sr\.?|ii|iii|iv|v)\s*$/i,''))}
function award(p){let arr=byI()[current]||[],n=namedSet(),dn=displayName(p);if(n.has(p.id)){$('message').textContent='You already named '+dn+'.';return}if(isRevealed(p.id)){$('message').textContent=dn+' was already revealed in this challenge, so it cannot count toward Players Named.';return}n.add(p.id);putNamed(new Set([...rawNamedSet(),p.id]));resetHint();$('hint').hidden=true;$('guess').value='';counts();stats();let remaining=arr.filter(x=>!n.has(x.id)&&!isRevealed(x.id)).length;if(remaining)$('message').textContent='✓ '+dn+' — '+remaining+' more unrevealed answer'+(remaining===1?'':'s')+' for '+current+'.';else{$('message').textContent='✓ '+dn+' — challenge cleared!';setTimeout(advance,1400)}}
function chooseAmbiguous(id){let p=(byI()[current]||[]).find(x=>x.id===id);if(p)award(p)}
function check(){let q=$('guess').value.trim();if(!q)return;let arr=byI()[current]||[],qn=norm(q),qb=normAnswer(q);
 let exactDisplay=arr.filter(x=>norm(displayName(x))===qn);if(exactDisplay.length===1){award(exactDisplay[0]);return}
 let matches=arr.filter(x=>norm(x.n)===qn||normAnswer(x.n)===qb||normAnswer(displayName(x))===qb);
 if(!matches.length){$('message').textContent='Not one we have for '+current+' in this challenge.';return}
 if(matches.length===1){award(matches[0]);return}
 $('message').innerHTML='<div class="ambiguityTitle">More than one player has that exact name. Which one did you mean?</div><div class="ambiguityNote">Choose using only the minimum detail needed to identify your answer.</div><div class="ambiguityChoices">'+matches.map(x=>`<button type="button" class="ghost ambiguityChoice" data-player-id="${esc(x.id)}">${esc(disambigLabel(x))}</button>`).join('')+'</div>';
 $('message').querySelectorAll('[data-player-id]').forEach(b=>b.onclick=()=>chooseAmbiguous(b.dataset.playerId));}
function target(){let n=namedSet(),r=(byI()[current]||[]).filter(p=>!n.has(p.id)&&!isRevealed(p.id));if(!r.length)return null;let p=r.find(x=>x.id===hintPlayerId)||r[Math.floor(Math.random()*r.length)];hintPlayerId=p.id;return p}function eraName(p){let y=teamYears(p);if(y[0]<=1999&&y[1]>=2000)return'Classic / Modern';if(y[1]<=1999)return'Classic';if(y[1]>=CURRENT-RECENT+1)return'Current / Modern';return'Modern'}function otherTeams(p){if(cfg.sport==='ALL')return p.sourceSports||[];let excluded=cfg.scope==='team'?[cfg.choice]:[];let book=teamBook();return p.career.filter(x=>!excluded.includes(x)).map(x=>book[x]?.name||x).filter(Boolean)}
function hint(){let p=target(),box=$('hint');box.hidden=false;if(!p){box.innerHTML='No unrevealed players remain for this combination.';return}if(hintLevel<4)hintLevel++;let y=teamYears(p),lines=[];if(hintLevel>=1)lines.push(`<div class="hintLine"><strong>Position:</strong> ${p.p||'Unknown'}</div>`);if(hintLevel>=2)lines.push(`<div class="hintLine"><strong>Era:</strong> ${eraName(p)}</div>`);let oth=otherTeams(p);if(hintLevel>=3)lines.push(`<div class="hintLine"><strong>Other teams:</strong> ${oth.length?oth.slice(0,5).join(', '):'No other current-franchise lineage'}</div>`);if(hintLevel>=4)lines.push(`<div class="hintLine"><strong>${meta().short} years:</strong> ${y[0]}${y[1]!==y[0]?'–'+y[1]:''}</div>`);let c=hintLevel<4?'':`<div class="hintWarning"><strong>Strong hint ahead</strong><div>The next clue reveals this player's first name.</div><button id="firstNameHint" class="ghost hintStrong">⚠️ Reveal First Name</button></div>`;box.innerHTML=`<div class="hintTitle">Hints for one remaining ${current} player</div>`+lines.join('')+c;if(hintLevel>=4)$('firstNameHint').onclick=firstName}
function firstName(){let p=target(),y=teamYears(p);firstNameShown=true;$('hint').innerHTML=`<div class="hintTitle">Same mystery player</div><div class="hintLine"><strong>Position:</strong> ${p.p||'Unknown'}</div><div class="hintLine"><strong>${meta().short} years:</strong> ${y[0]}${y[1]!==y[0]?'–'+y[1]:''}</div><div class="hintLine"><strong>First name:</strong> ${p.n.split(/\s+/)[0]}</div><div class="hintWarning"><strong>Still stuck?</strong><div>Revealing the full player will make this answer ineligible for Players Named in this challenge.</div><button id="revealPlayer" class="ghost hintStrong">🏳️ Reveal Player</button></div>`;$('revealPlayer').onclick=revealPlayer}
function revealPlayer(){let p=target(),r=revealMap(),k=contextKey();r[k]=[...new Set([...(r[k]||[]),p.id])];putReveal(r);$('hint').innerHTML=`<div class="hintTitle">Revealed player</div><div class="revealed">${displayName(p)}</div><div class="revealNote">This answer cannot count toward Players Named in this challenge.</div>`;counts();stats()}
function defer(){advance()}function jump(){let t=$('firstLetter').value+$('lastLetter').value;current=t;let ss=seq(),n=ss.indexOf(t);if(n>=0)idx=n;render();$('settingsModal').hidden=true}
for(let id of ['firstLetter','lastLetter'])for(let l of L){let o=document.createElement('option');o.value=o.textContent=l;$(id).appendChild(o)}$('firstLetter').value='N';$('lastLetter').value='S';$('jumpBtn').onclick=jump;$('submit').onclick=check;$('hintBtn').onclick=hint;$('later').onclick=defer;$('guess').onkeydown=e=>{if(e.key==='Enter')check()};$('namedToggle').onclick=()=>{namedOpen=!namedOpen;renderNamed()};document.querySelectorAll('[data-sport]').forEach(b=>b.classList.toggle('active',b.dataset.sport===cfg.sport));document.querySelectorAll('[data-sport]').forEach(b=>b.onclick=()=>setSport(b.dataset.sport));document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>setScope(b.dataset.scope));document.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>setEra(b.dataset.era));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('settingsBtn').onclick=()=>$('settingsModal').hidden=false;$('closeSettings').onclick=()=>$('settingsModal').hidden=true;$('resetReveal').onclick=()=>$('resetConfirm').hidden=false;$('cancelReset').onclick=()=>$('resetConfirm').hidden=true;$('reset').onclick=()=>{localStorage.removeItem(NAMED_KEY);localStorage.setItem(MIGRATED_KEY,'1');location.reload()};$('settingsModal').onclick=e=>{if(e.target===$('settingsModal'))$('settingsModal').hidden=true};window.addEventListener('aa-nfl-progress',e=>{if(cfg.sport==='NFL')$('dataStatus').textContent=`Loading NFL history… ${e.detail.done}/${e.detail.total} seasons`});Promise.resolve(window.AA_ROSTER_READY).catch(()=>null).finally(async()=>{migrateProgress();if(cfg.sport==='NFL'||cfg.sport==='ALL'){try{$('dataStatus').textContent='Loading NFL history…';await window.loadNFLPlayers();$('dataStatus').textContent='NFL historical rosters are built into V4.4.'}catch(e){$('dataStatus').textContent='NFL data could not load. Switch to MLB or check your connection.'}}if(cfg.sport==='ALL'){cfg.scope='league';cfg.choice='ALL'}buildChoices();pick();});
