(()=>{'use strict';
const key='aa-v453-celebrations';let options={sound:'sport',volume:60,visual:true};try{Object.assign(options,JSON.parse(localStorage.getItem(key)||'{}'))}catch{}
function save(){localStorage.setItem(key,JSON.stringify(options))}
function bind(){const s=document.getElementById('celebrationSound'),v=document.getElementById('celebrationVolume'),l=document.getElementById('celebrationVolumeLabel'),c=document.getElementById('celebrationVisual');if(!s)return;s.value=options.sound;v.value=options.volume;l.textContent=options.volume+'%';c.checked=options.visual;s.onchange=()=>{options.sound=s.value;save()};v.oninput=()=>{options.volume=+v.value;l.textContent=v.value+'%';save()};c.onchange=()=>{options.visual=c.checked;save()}}
function editDistance(a,b){if(Math.abs(a.length-b.length)>2)return 9;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let row=[i];for(let j=1;j<=b.length;j++){let v=Math.min(row[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));if(i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])v=Math.min(v,prev[j-2]+1);row.push(v)}prev=row}return prev[b.length]}
function words(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z\s-]/g,' ').trim().split(/[\s-]+/).filter(Boolean).filter(x=>!['jr','sr','ii','iii','iv'].includes(x))}
window.AA_FUZZY=(typed,players,display)=>{const w=words(typed);if(w.length<2)return[];const eligible=players.filter(p=>{const target=words(display(p));if(target.length<2||w.length!==target.length)return false; // Require correctly matching first/last initials, even when misspelled.
if(w[0][0]!==target[0][0]||w[w.length-1][0]!==target[target.length-1][0])return false;
let distance=0;for(let i=0;i<w.length;i++){let d=editDistance(w[i],target[i]);if(d>1&&!(w[i].length>=9&&d===2))return false;distance+=d}return distance>0&&distance<=2});return eligible.length===1?eligible:eligible};
let ctx=null;function tone(f,t,d,kind='sine',gain=.12){if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=kind;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+d+.02)}
function noise(t,d,gain=.1){if(!ctx)return;const n=Math.ceil(ctx.sampleRate*d),b=ctx.createBuffer(1,n,ctx.sampleRate),data=b.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*Math.exp(-4*i/n);const src=ctx.createBufferSource(),g=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1500;src.buffer=b;g.gain.value=gain;src.connect(filter);filter.connect(g);g.connect(ctx.destination);src.start(t)}
function sound(sport,level){if(options.sound==='off'||!options.volume)return;try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();const t=ctx.currentTime+.03,m=options.volume/100,mode=options.sound==='crowd'?'ALL':sport;const cheer=()=>{for(let i=0;i<(level==='initials'?5:12);i++)noise(t+.1+i*.085,.24,.055*m)};
if(mode==='MLB'){noise(t,.13,.25*m);tone(240,t+.1,.18,'triangle',.11*m);cheer()}
else if(mode==='NBA'){tone(1100,t,.10,'sine',.09*m);tone(700,t+.12,.15,'sine',.09*m);cheer()}
else if(mode==='NFL'){tone(392,t,.14,'square',.045*m);tone(523,t+.16,.2,'square',.045*m);tone(784,t+.38,.27,'square',.045*m);cheer()}
else if(mode==='NHL'){tone(220,t,.35,'sawtooth',.08*m);tone(277,t+.1,.35,'sawtooth',.07*m);tone(330,t+.2,.35,'sawtooth',.07*m);cheer()}
else{tone(392,t,.14,'triangle',.09*m);tone(523,t+.15,.18,'triangle',.09*m);tone(784,t+.34,.28,'triangle',.09*m);cheer()}
}catch(e){}}
let last=0;window.AA_CELEBRATE=(level,sport)=>{if(Date.now()-last<1000)return;last=Date.now();sound(sport,level);if(!options.visual)return;let el=document.createElement('div');el.className='aa-celebration';el.setAttribute('role','status');el.innerHTML='<div class="aa-celebration-inner"><div class="aa-celebration-trophy">🏆</div><strong>'+(level==='initials'?'INITIALS MASTERED!':'LETTER COMPLETED!')+'</strong><span>Fantastic work!</span></div>';for(let i=0;i<22;i++){let c=document.createElement('i');c.className='aa-confetti';c.style.left=(Math.random()*100)+'%';c.style.animationDelay=(Math.random()*.35)+'s';c.style.background=['#f7b64d','#52c7c2','#fff','#ed7b62'][i%4];el.append(c)}document.body.append(el);setTimeout(()=>el.remove(),level==='initials'?1700:2400)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();