(()=>{'use strict';
const KEY='aa-v33-named-athletes',TEAM='aa_teams_az_v1';const $=id=>document.getElementById(id);
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=document.createElement('style');style.textContent=`#aa45{max-width:760px;margin:18px auto;padding:0 12px;color:#f4f7fa;font:inherit}#aa45 details{background:#17232b;border:1px solid #647783;border-radius:14px;padding:14px;margin:12px 0}#aa45 summary{font-weight:800;cursor:pointer}#aa45 button,#aa45 select,#aa45 input,#aa45 textarea{font:inherit;box-sizing:border-box}#aa45 button{padding:10px 12px;border:1px solid #91a9b5;border-radius:9px;background:#26414d;color:white;margin:6px 4px 6px 0}#aa45 input,#aa45 select,#aa45 textarea{background:#101920;color:white;border:1px solid #8ca0a9;border-radius:8px;padding:10px;max-width:100%}#aa45 input[type=search],#aa45 textarea{width:100%}#aa45 .small{font-size:.87rem;color:#b8cbd4}#aa45 .aa45list{max-height:240px;overflow:auto;line-height:1.65}#aa45 .aa45row{padding:5px 0;border-bottom:1px solid #33424b}#aa45 .aa45grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}#aa45 .aa45metric{padding:10px;background:#20313b;border-radius:10px}#aa45 .aa45metric b{display:block;font-size:1.2rem}#aa45 .warning{color:#ffd9a6}#aa45 label{display:block;margin-top:9px}#aa45 button:focus-visible{outline:3px solid #5ccdd2}`;document.head.appendChild(style);
const root=document.createElement('section');root.id='aa45';root.innerHTML=`<h2>Game Tools · V4.5</h2>
<details><summary>💾 Backup & Restore Progress</summary><p class="small">Save a JSON backup of all Athlete Alphabet browser progress and settings. Restore only from a backup you trust. Existing progress is not changed by exporting.</p><button id="aaExport">Download Backup</button><label for="aaImport">Choose backup to restore</label><input id="aaImport" type="file" accept=".json,application/json"><p id="aaBackupStatus" class="small"></p><div id="aaRestoreBox" hidden><p class="warning">Restore will replace existing Athlete Alphabet saved data on this device. Export a backup first.</p><button id="aaRestoreYes">Confirm Restore</button><button id="aaRestoreNo">Cancel</button></div></details>
<details><summary>🔎 Search Already Named Answers</summary><label>Search by name <input id="aaSearch" type="search" placeholder="Search named answers only"></label><label>Sport <select id="aaFilter"><option value="ALL">All Sports</option><option>MLB</option><option>NFL</option><option>NBA</option><option>NHL</option><option value="TEAMS">Teams A–Z</option></select></label><label>First letter <select id="aaLetter"><option value="ALL">All letters</option></select></label><p id="aaSearchCount" class="small"></p><div id="aaSearchResults" class="aa45list"></div></details>
<details><summary>📊 Progress Dashboard</summary><div id="aaDashboard" class="aa45grid"></div><p class="small">Named athletes are counted by sport. A multi-sport athlete may appear in more than one sport's totals. Database counts are not guaranteed to be exhaustive.</p></details>
<details><summary>🧪 Game Consistency Check</summary><button id="aaCheck">Run Local Checks</button><div id="aaCheckResults" class="aa45list small"></div><p class="small">Checks loaded data, duplicate IDs, team sorting, and saved-data readability. This is not a full automated playthrough of every game mode.</p></details>
<details><summary>📝 Report a Missing or Incorrect Answer</summary><p class="small">Creates a report you can copy or save. It does not send data anywhere automatically.</p><label>Type <select id="aaReportType"><option>Missing athlete</option><option>Incorrect athlete/team affiliation</option><option>Missing team</option><option>Incorrect team nickname or letter</option><option>Other</option></select></label><label>Sport <select id="aaReportSport"><option>MLB</option><option>NFL</option><option>NBA</option><option>NHL</option><option>All Sports</option></select></label><label>Name <input id="aaReportName" placeholder="Name of athlete or team"></label><label>Team / Era / Letter <input id="aaReportContext" placeholder="Relevant team, era, letter"></label><label>Notes <textarea id="aaReportNotes" rows="3" placeholder="What happened? What should be accepted?"></textarea></label><button id="aaReportCopy">Copy Report</button><button id="aaReportSave">Save Report</button><p id="aaReportStatus" class="small"></p></details>`;
const advanced=$('advancedTools');advanced?.appendChild(root);const heading=root.querySelector('h2');if(heading)heading.remove();
for(const c of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'){let o=document.createElement('option');o.value=o.textContent=c;$('aaLetter').appendChild(o)}
const download=(name,text,type)=>{const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000)};
const ownedKeys=()=>Object.keys(localStorage).filter(k=>k.startsWith('aa-')||k.startsWith('aa_'));
$('aaExport').onclick=()=>{const data={format:'athlete-alphabet-backup',schema:1,created:new Date().toISOString(),values:{}};for(const k of ownedKeys())data.values[k]=localStorage.getItem(k);download('AthleteAlphabet-Progress-Backup.json',JSON.stringify(data,null,2),'application/json');$('aaBackupStatus').textContent='Backup prepared. Keep the file somewhere safe.'};
let pending=null;$('aaImport').onchange=async()=>{pending=null;$('aaRestoreBox').hidden=true;try{const f=$('aaImport').files[0];if(!f)return;const obj=JSON.parse(await f.text());if(obj.format!=='athlete-alphabet-backup'||obj.schema!==1||!obj.values||typeof obj.values!=='object'||Array.isArray(obj.values))throw Error('Unrecognized backup format');const keys=Object.keys(obj.values);if(!keys.length||keys.length>5000||keys.some(k=>!(k.startsWith('aa-')||k.startsWith('aa_'))||typeof obj.values[k]!=='string'))throw Error('Invalid backup data');pending=obj;$('aaBackupStatus').textContent=`Backup from ${obj.created||'unknown date'} contains ${keys.length} saved entries.`;$('aaRestoreBox').hidden=false}catch(e){$('aaBackupStatus').textContent='Cannot load backup: '+e.message}};
$('aaRestoreNo').onclick=()=>{pending=null;$('aaRestoreBox').hidden=true};$('aaRestoreYes').onclick=()=>{if(!pending)return;try{const entries=Object.entries(pending.values);const snapshot={};for(const k of ownedKeys())snapshot[k]=localStorage.getItem(k);try{for(const k of ownedKeys())localStorage.removeItem(k);for(const [k,v] of entries)localStorage.setItem(k,v)}catch(e){for(const k of ownedKeys())localStorage.removeItem(k);for(const [k,v] of Object.entries(snapshot))localStorage.setItem(k,v);throw e}location.reload()}catch(e){$('aaBackupStatus').textContent='Restore failed; prior data recovered: '+e.message}};
const lists=()=>[['MLB',window.ATHLETE_PLAYERS||[]],['NFL',window.NFL_PLAYERS||[]],['NBA',window.NBA_PLAYERS||[]],['NHL',window.NHL_PLAYERS||[]]];
const names=()=>{const named=new Set(read(KEY,[]));const found=[];const seen=new Set();for(const [sport,players] of lists())for(const p of players){if(!named.has(p.id)||seen.has(sport+':'+p.id))continue;seen.add(sport+':'+p.id);found.push({sport,name:p.n||p.name||p.id,letter:(p.i||'')[0]||'',id:p.id})}for(const t of window.AA_TEAMS||[])if(read(TEAM,{})[t.id])found.push({sport:'TEAMS',name:t.name,letter:t.nickname==='49ers'?'F':t.nickname==='76ers'?'S':t.nickname[0]?.toUpperCase()||'',id:t.id});return found};
function search(){const q=$('aaSearch').value.trim().toLowerCase(),s=$('aaFilter').value,l=$('aaLetter').value;const result=names().filter(p=>(s==='ALL'||p.sport===s)&&(l==='ALL'||p.letter===l)&&p.name.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));$('aaSearchCount').textContent=result.length+' already named answer(s)';$('aaSearchResults').innerHTML=result.slice(0,400).map(p=>`<div class="aa45row">${esc(p.name)} <span class="small">· ${esc(p.sport)}</span></div>`).join('')||(result.length?'':'No matching named answers.');if(result.length>400)$('aaSearchResults').insertAdjacentHTML('beforeend','<p class="small">Showing first 400 matches. Narrow your search.</p>')}
for(const id of ['aaSearch','aaFilter','aaLetter'])$(id).addEventListener(id==='aaSearch'?'input':'change',search);
function dashboard(){const named=new Set(read(KEY,[])),teamSaved=read(TEAM,{}),teams=window.AA_TEAMS||[];const cells=lists().map(([sport,a])=>{const ids=new Set(a.map(p=>p.id));return [sport,[...ids].filter(id=>named.has(id)).length,ids.size]});cells.push(['Teams A–Z',teams.filter(t=>teamSaved[t.id]).length,teams.length]);$('aaDashboard').innerHTML=cells.map(([s,n,t])=>`<div class="aa45metric"><span>${esc(s)}</span><b>${n.toLocaleString()} / ${t.toLocaleString()}</b><span class="small">${t?(100*n/t).toFixed(1):'0'}% named</span></div>`).join('')}
function checks(){const results=[];const check=(label,ok,detail='')=>results.push(`<div class="aa45row">${ok?'✓':'⚠'} ${esc(label)}${detail?' — '+esc(detail):''}</div>`);for(const [sport,a] of lists()){const ids=a.map(p=>p.id);check(sport+' loaded',a.length>0,a.length+' records');check(sport+' IDs present',ids.every(Boolean));check(sport+' duplicate IDs',new Set(ids).size===ids.length,new Set(ids).size+' unique of '+ids.length)}const teams=window.AA_TEAMS||[];check('Teams loaded',teams.length===124,teams.length+' teams');check('Unique team IDs',new Set(teams.map(t=>t.id)).size===teams.length);for(const [id,expected] of [['NHL:CBJ','B'],['NBA:POR','T']]){const t=teams.find(x=>x.id===id);check(id+' letter',!!t&&(t.nickname==='49ers'?'F':t.nickname==='76ers'?'S':t.nickname[0].toUpperCase())===expected,t?.nickname||'not found')}for(const k of [KEY,TEAM]){let valid=true;try{JSON.parse(localStorage.getItem(k)||'null')}catch{valid=false}check(k+' readable',valid)}$('aaCheckResults').innerHTML=results.join('');dashboard()}
$('aaCheck').onclick=checks;
const report=()=>`Athlete Alphabet V4.5.1 issue report\nType: ${$('aaReportType').value}\nSport: ${$('aaReportSport').value}\nName: ${$('aaReportName').value.trim()}\nTeam / Era / Letter: ${$('aaReportContext').value.trim()}\nNotes: ${$('aaReportNotes').value.trim()}\nReported: ${new Date().toISOString()}\n`;
$('aaReportCopy').onclick=async()=>{try{await navigator.clipboard.writeText(report());$('aaReportStatus').textContent='Report copied. Paste it into our chat.'}catch(e){$('aaReportStatus').textContent='Clipboard unavailable. Use Save Report instead.'}};
$('aaReportSave').onclick=()=>{download('AthleteAlphabet-Issue-Report.txt',report(),'text/plain');$('aaReportStatus').textContent='Report saved. Share it here when ready.'};
for(const d of root.querySelectorAll('details'))d.addEventListener('toggle',()=>{if(d.open){search();dashboard()}});
})();